- name: enable lingering for deploy user
  command: loginctl enable-linger {{deploy_user}}

# - name: install systemd unit
#   template:
#     src: "{{role_path}}/templates/sidekiq-production.service"
#     dest: "/etc/systemd/system/sidekiq-{{app_name}}.service"

# - name: enable systemd unit
#   systemd:
#     name: "sidekiq-{{app_name}}"
#     daemon_reload: true
#     enabled: true
#     state: started
