---
- name: install certbot
  apt:
    name: "{{item}}"
  with_items:
    - certbot
    - python3-certbot-nginx
  tags:
    - packages

- stat:
    path: /etc/letsencrypt/live/{{domain}}/fullchain.pem
  register: letsencrypt_fullchain

- name: generate cert for domain
  command: certbot --noninteractive -m {{letsencrypt_email}} --agree-tos --standalone --preferred-challenges http certonly -d {{domain}}
  when: not letsencrypt_fullchain.stat.exists
