---
- name: install certbot
  apt:
    name: "{{item}}"
  with_items:
    - certbot
    - python3-certbot-nginx
  tags:
    - packages

# certbot --noninteractive -m mail@intelaxy.ru --agree-tos --nginx certonly -d api.inventoryapp.info
