---
- name: Create deploy user
  user:
    name: "{{deploy_user}}"
    shell: /bin/bash

- name: install packages
  apt:
    name: "{{item}}"
  loop:
    - libpq-dev
    - git
    - build-essential
    - patch
    - zlib1g-dev
    - liblzma-dev
  tags:
    - packages

- name: delete .bashrc_custom
  file:
    path: /home/{{deploy_user}}/.bashrc_custom
    state: absent

- name: directory
  file:
    path: "{{app_path}}"
    state: directory
    owner: "{{deploy_user}}"
    group: "{{deploy_user}}"
    mode: 0777

- name: webpack
  npm:
    name: webpack
    global: yes
  when: railsapp_webpack

- name: install rpush unit
  template:
    src: "{{role_path}}/templates/rpush.service"
    dest: /home/{{deploy_user}}/.config/systemd/user/rpush.service
    owner: "{{deploy_user}}"
    group: "{{deploy_user}}"
    mode: 0600
  when: rpush
  tags: rpush
# systemctl --user daemon-reload
- name: enable rpush unit
  systemd:
    name: rpush
    state: started
    enabled: yes
    scope: user
    # daemon_reload: yes
  become: yes
  become_user: "{{deploy_user}}"
  # become_method: su
  when: rpush
  # tags: rpush

- debug:
    var: rails_env
    verbosity: 2
  tags: debug
