---
- name: Create deploy user
  user:
    name: "{{deploy_user}}"
    shell: /bin/bash

- name: install packages
  apt:
    name: "{{item}}"
  loop:
    - libpq-dev
    - git
    - build-essential
    - patch
    - zlib1g-dev
    - liblzma-dev
  tags:
    - packages

- name: delete .bashrc_custom
  file:
    path: /home/{{deploy_user}}/.bashrc_custom
    state: absent

- name: directory
  file:
    path: "{{app_path}}"
    state: directory
    owner: "{{deploy_user}}"
    group: "{{deploy_user}}"
    mode: 0777

- name: webpack
  npm:
    name: webpack
    global: yes
  when: railsapp_webpack
