---
- name: Create deploy user
  user:
    name: "{{deploy_user}}"
    shell: /bin/bash

- name: install packages
  apt:
    name: "{{item}}"
  loop:
    - libpq-dev
    - git
    - build-essential
    - patch
    - zlib1g-dev
    - liblzma-dev
  tags:
    - packages

- name: .bashrc_custom
  lineinfile:
    create: true
    owner: "{{deploy_user}}"
    group: "{{deploy_user}}"
    path: /home/{{deploy_user}}/.bashrc_custom
    line: "{{ item }}"
  loop:
    - export RAILS_ENV=production
    - alias r=rails
    - PATH=$PATH:/home/{{deploy_user}}/.gem/ruby/{{ruby_version}}.0/bin/

- name: directory
  file:
    path: "{{app_path}}"
    state: directory
    owner: "{{deploy_user}}"
    group: "{{deploy_user}}"
    mode: 0777

- name: webpack
  npm:
    name: webpack
    global: yes
  when: railsapp_webpack
