- name: install rssh
  apt:
    name: "{{item}}"
  with_items:
    - rssh
  tags:
    - packages

- name: user external_backup
  user:
    name: "{{backup_server.user}}"
    shell: /usr/bin/rssh

- name: ssh key
  authorized_key:
    user: "{{backup_server.user}}"
    state: present
    key: "{{ backup_server.remote_backup_pub_key }}"

- name: allow rsync and scp
  lineinfile:
    dest: /etc/rssh.conf
    line: "{{ item }}"
    state: present
  with_items:
    - allowrsync
    - allowscp

- name: backup folders
  file:
    path: "{{item}}"
    owner: "{{backup_server.user}}"
    group: "{{backup_server.user}}"
    mode: 0700
    state: directory
  with_items: "{{ backup_server.folders }}"
