---
- name: Add Phusion Passenger repository key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 561F9B9CAC40B2F7
- name: Add Phusion Passenger repository
  apt_repository:
    repo: deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ansible_distribution_release}} main
    state: present
- name: Install Phusion Passenger
  apt:
    name: "{{item}}"
    update_cache: yes
  with_items:
    - nginx-extras
    - passenger
- name: Enable Phusion Passenger
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: 'passenger\.conf'
    line: 'include /etc/nginx/passenger.conf;'
- name: env PATH in nginx.conf for nodejs
  lineinfile:
    path: /etc/nginx/nginx.conf
    line: 'env PATH;'
    state: present
    insertbefore: '^user'
- name: Site config
  template:
    src: "{{role_path}}/templates/site.conf.j2"
    dest: /etc/nginx/sites-enabled/{{app_name}}
    mode: 0600
  notify: restart nginx
