---
- name: /root/.bashrc
  copy:
    src: "{{role_path}}/files/.bashrc"
    dest: /root/.bashrc
    owner: root
    group: root
    mode: 0600

# - name: bashrc skeleton file
#   copy:
#     src: "{{role_path}}/files/.bashrc"
#     dest: /etc/skel/.bashrc
#     owner: root
#     group: root
#     mode: 0644

- name: bashrc for deploy_user
  copy:
    src: "{{role_path}}/files/.bashrc"
    dest: /home/{{deploy_user}}/.bashrc
    owner: "{{deploy_user}}"
    group: "{{deploy_user}}"
    mode: 0600
  when: deploy_user is defined

- name: input.rc
  blockinfile:
    path: /etc/inputrc
    block: |
      "\t":menu-complete
      "\e[A":history-search-backward
      "\e[B":history-search-forward
      set show-all-if-ambiguous on

- name: .bashrc_deploy_user
  template:
    src: "{{role_path}}/templates/.bashrc_deploy_user"
    dest: /home/{{deploy_user}}/.bashrc_deploy_user
    owner: "{{deploy_user}}"
    group: "{{deploy_user}}"
    mode: 0600
  when: deploy_user is defined
