---
- name: Bitcoind PPA
  apt_repository:
    repo: ppa:bitcoin/bitcoin
- name: Install bitcoind
  apt:
    name: bitcoind
    update_cache: yes
- name: .bitcoin directory
  file:
    path: /home/{{deploy_user}}/.bitcoin
    state: directory
    owner: "{{deploy_user}}"
    group: "{{deploy_user}}"
    mode: 0700
- name: bitcoind.conf
  template:
    src: "{{role_path}}/templates/bitcoin.conf.j2"
    dest: /home/{{deploy_user}}/.bitcoin/bitcoin.conf
    owner: "{{deploy_user}}"
    group: "{{deploy_user}}"
    mode: 0600
