---
- name: Allow ports TCP
  ufw:
    rule: allow
    proto: tcp
    port: "{{item}}"
  with_items:
    - 22
    - 80
    - 443
- name: Enable ufw
  ufw:
    state: enabled
    policy: deny
    direction: incoming
